/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        'surface': '#f7f9fb',
        'surface-dim': '#d8dadc',
        'surface-bright': '#f7f9fb',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f2f4f6',
        'surface-container': '#eceef0',
        'surface-container-high': '#e6e8ea',
        'surface-container-highest': '#e0e3e5',
        'on-surface': '#191c1e',
        'on-surface-variant': '#454651',
        'inverse-surface': '#2d3133',
        'inverse-on-surface': '#eff1f3',
        'outline': '#767682',
        'outline-variant': '#c6c5d3',
        'surface-tint': '#4b57aa',
        'surface-variant': '#e0e3e5',
        'primary': '#142175',
        'on-primary': '#ffffff',
        'primary-container': '#2e3a8c',
        'on-primary-container': '#9ea9ff',
        'inverse-primary': '#bcc3ff',
        'primary-fixed': '#dfe0ff',
        'primary-fixed-dim': '#bcc3ff',
        'on-primary-fixed': '#000d60',
        'on-primary-fixed-variant': '#333f91',
        'secondary': '#006c49',
        'on-secondary': '#ffffff',
        'secondary-container': '#6cf8bb',
        'on-secondary-container': '#00714d',
        'secondary-fixed': '#6ffbbe',
        'secondary-fixed-dim': '#4edea3',
        'on-secondary-fixed': '#002113',
        'on-secondary-fixed-variant': '#005236',
        'tertiary': '#610009',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#8b0012',
        'on-tertiary-container': '#ff9089',
        'tertiary-fixed': '#ffdad7',
        'tertiary-fixed-dim': '#ffb3ad',
        'on-tertiary-fixed': '#410004',
        'on-tertiary-fixed-variant': '#930013',
        'error': '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'background': '#f7f9fb',
        'on-background': '#191c1e',
        // Dark mode overrides
        'dark-bg': '#0F172A',
        'dark-surface': '#1E293B',
        // Semantic colors
        'success': '#10B981',
        'danger': '#EF4444',
      },
      borderRadius: {
        'sm': '0.25rem',
        'DEFAULT': '0.5rem',
        'md': '0.75rem',
        'lg': '1rem',
        'xl': '1.5rem',
        '2xl': '1.5rem',
        'full': '9999px',
      },
      spacing: {
        'gutter': '1rem',
        'touch-target-min': '48px',
        'container-margin': '1rem',
        'stack-sm': '0.5rem',
        'stack-md': '1rem',
        'stack-lg': '1.5rem',
      },
      fontFamily: {
        'geist': ['Geist', 'system-ui', 'sans-serif'],
        'inter': ['Inter', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'numeric-display': ['28px', { lineHeight: '32px', letterSpacing: '-0.02em', fontWeight: '700' }],
      },
      boxShadow: {
        'soft': '0px 4px 12px rgba(0, 0, 0, 0.05)',
        'elevated': '0px 12px 24px rgba(0, 0, 0, 0.1)',
      },
    },
  },
  plugins: [],
}
